### ISSUE TITLE
Great project

### ISSUE THREAD

**Issue by RobinXL** [ssampang/im2latex#1]
Can you include the predict function so that I can test on a single image? appreciate!

**Comment by ssampang** [comment]
Hi Robin,

In the code, I calculate whether the prediction of the model was correct on line 207 in order to calculate the accuracy. To get the actual output, just modify that line into `correct_prediction = tf.to_int32(tf.argmax( output, 2))`. That gives you the integer codes of each latex token. The mapping from integers to tokens is contained in latex_vocab.txt (in the `data` folder), so that's simply a matter of doing lookups. Keep in mind that the model is currently setup to run on batches of size 20, so you'll have to pad your arrays to that size if you don't have 20 images to run at the same time.
